### ISSUE TITLE
Dynamic Attribute lookup

### ISSUE THREAD

**Issue by pvizeli** [acrisci/python-dbus-next#11]
Hi acrisci,

Thanks for your library. I currently work on a replacement of my old code with your library.

I see that you modify the object dynamic on runtime which eats a lot of resources. I will point to my old dbus implementation they use a more pythonic way to provide such service:
https://github.com/home-assistant/hassio/blob/181/hassio/utils/gdbus.py#L192

I lookup the interface dynamic to the proxy object, that allows using syntax like: object.Manager.functionCall() -> (org.freedesktop.systemd1.Manager).

Anyway, I like your work and that should be only a tip from developer to developer and no critic.

**Comment by acrisci** [comment]
Yeah there are a lot of different ways to do this. Calling general functions is something I would definitely put in the library if someone implemented it.

Another great way to do this is with code generation because that way you get completion and type checking too. I'll open an issue for that as well.
